[book]
authors = ["Ankitects Pty Ltd and contributors"]
description = "Anki 使用手冊。Anki 是一個閃卡程式，是你學習時的好幫手。"
language = "zh-tw"
multilingual = false
src = "src"
title = "Anki 使用手冊"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/anki-manual-zh-tw/anki-manual/"
cname = "lghhz.github.io/anki-manual"
additional-css = ["css/kbd.css", "css/misc.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [
  'microsoft.com',
  'twitter.com',
  'stackexchange.com',
  'stackoverflow.com',
  'https://github.com/open-spaced-repetition/fsrs4anki#add-on-compatibility',
  'support.google.com',
  'wikiwiki.jp',
]

[output.html.fold]
enable = true
level = 0
